### ISSUE TITLE
`in-order-to test-op` missing

### ISSUE THREAD

**Issue by Ambrevar** [omar-polo/phos#8]
Currently calling `asdf:test-system` on `phos` does nothing, because the `phos` system is missing this line:

```lisp
:in-order-to ((test-op (test-op "phos/test")))
```

**Comment by omar-polo** [comment]
I didn't know one can test a system with `asdf:test-system` (I'm still learning!).  Is 6620b82b091cdfed655e1093ef045dbe518d5474 enough?  With that I can successfully run the test suite with `(asdf:test-system :phos)` from a fresh repl.

thanks :)

**Comment by Ambrevar** [comment]
That's perfect, thanks!
